version: '3'
services:
  web:
    image: nginx:alpine
    container_name: crawler-web
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
      - ./.docker/nginx/default.template.conf:/etc/nginx/conf.d/default.template
    ports:
      - 8080:80
    environment:
      - NGINX_HOST=crawler.web
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php-fpm
      - db
    networks:
      crawler:
        ipv4_address: 175.17.0.11
  php-fpm:
    build: .docker/php-fpm
    container_name: crawler-php
    restart: always
    volumes:
      - ./:/var/www/html
      - ./.docker/php-fpm/php-fpm.conf:/etc/php/7.3/fpm/php-fpm.conf
      - ./.docker/php-fpm/php-fpm.d/:/etc/php/7.3/fpm/pool.d/
      - ./.docker/php-fpm/php.ini:/etc/php/7.3/fpm/php.ini
      - ./.docker/php-fpm/xdebug.ini:/etc/php/7.3/mods-available/xdebug.ini
      - $SSH_AUTH_SOCK:/ssh-agent
    ports:
      - 9000:9000
    environment:
      - SSH_AUTH_SOCK=/ssh-auth.sock
    networks:
      crawler:
        ipv4_address: 175.17.0.2
  db:
    image: mysql:5.7
    container_name: crawler-db
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./.data/db/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=crawler
      - MYSQL_DATABASE=crawler_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    networks:
      crawler:
        ipv4_address: 175.17.0.3
networks:
  crawler:
    driver: bridge
    ipam:
      config:
        - subnet: 175.17.0.0/16