# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.

    PHPHtmlParser\:
        resource: '../vendor/paquettg/php-html-parser/src/PHPHtmlParser'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
#    App\Controller\:
#        resource: '../src/Controller'
#        tags: ['controller.service_arguments']

    App\Controller\PageInfoController:
        arguments:
            - '@app.repository.parsed_page_info_repository'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    app.command.crawler_command:
        class: 'App\Command\CrawlerCommand'
        arguments:
            - '@app.service.recursive_parse_pages_service'
        tags: ['console.command']
    app.service.parse_page_service:
        class: 'App\Service\ParsePageService'
        arguments:
            - '@dom'
            - '@app.service.domain_service'
            - '@app.service.image_service'
    app.service.recursive_parse_pages_service:
        class: 'App\Service\RecursiveParsePagesService'
        arguments:
            - '@app.service.parse_page_service'
            - '@app.service.domain_service'
            - '@doctrine.orm.entity_manager'
    app.service.image_service:
        class: 'App\Service\ImageService'
        arguments:
            - '@app.service.domain_service'
    app.service.domain_service:
        class: 'App\Service\DomainService'
    dom:
        class: 'PHPHtmlParser\Dom'
    app.repository.parsed_page_info_repository:
        class: 'App\Repository\ParsedPageInfoRepository'
        arguments:
            ['@doctrine']
        tags: ['doctrine.repository_service']
